// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/src/api/models"
)

// PublicAPIServiceDeleteAPIKeysReader is a Reader for the PublicAPIServiceDeleteAPIKeys structure.
type PublicAPIServiceDeleteAPIKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicAPIServiceDeleteAPIKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicAPIServiceDeleteAPIKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPublicAPIServiceDeleteAPIKeysForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPublicAPIServiceDeleteAPIKeysNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPublicAPIServiceDeleteAPIKeysDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPublicAPIServiceDeleteAPIKeysOK creates a PublicAPIServiceDeleteAPIKeysOK with default headers values
func NewPublicAPIServiceDeleteAPIKeysOK() *PublicAPIServiceDeleteAPIKeysOK {
	return &PublicAPIServiceDeleteAPIKeysOK{}
}

/*
PublicAPIServiceDeleteAPIKeysOK describes a response with status code 200, with default header values.

A successful response.
*/
type PublicAPIServiceDeleteAPIKeysOK struct {
	Payload *models.V1ActivityResponse
}

// IsSuccess returns true when this public Api service delete Api keys o k response has a 2xx status code
func (o *PublicAPIServiceDeleteAPIKeysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this public Api service delete Api keys o k response has a 3xx status code
func (o *PublicAPIServiceDeleteAPIKeysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service delete Api keys o k response has a 4xx status code
func (o *PublicAPIServiceDeleteAPIKeysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this public Api service delete Api keys o k response has a 5xx status code
func (o *PublicAPIServiceDeleteAPIKeysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service delete Api keys o k response a status code equal to that given
func (o *PublicAPIServiceDeleteAPIKeysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the public Api service delete Api keys o k response
func (o *PublicAPIServiceDeleteAPIKeysOK) Code() int {
	return 200
}

func (o *PublicAPIServiceDeleteAPIKeysOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] publicApiServiceDeleteApiKeysOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] publicApiServiceDeleteApiKeysOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysOK) GetPayload() *models.V1ActivityResponse {
	return o.Payload
}

func (o *PublicAPIServiceDeleteAPIKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceDeleteAPIKeysForbidden creates a PublicAPIServiceDeleteAPIKeysForbidden with default headers values
func NewPublicAPIServiceDeleteAPIKeysForbidden() *PublicAPIServiceDeleteAPIKeysForbidden {
	return &PublicAPIServiceDeleteAPIKeysForbidden{}
}

/*
PublicAPIServiceDeleteAPIKeysForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type PublicAPIServiceDeleteAPIKeysForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this public Api service delete Api keys forbidden response has a 2xx status code
func (o *PublicAPIServiceDeleteAPIKeysForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service delete Api keys forbidden response has a 3xx status code
func (o *PublicAPIServiceDeleteAPIKeysForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service delete Api keys forbidden response has a 4xx status code
func (o *PublicAPIServiceDeleteAPIKeysForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service delete Api keys forbidden response has a 5xx status code
func (o *PublicAPIServiceDeleteAPIKeysForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service delete Api keys forbidden response a status code equal to that given
func (o *PublicAPIServiceDeleteAPIKeysForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the public Api service delete Api keys forbidden response
func (o *PublicAPIServiceDeleteAPIKeysForbidden) Code() int {
	return 403
}

func (o *PublicAPIServiceDeleteAPIKeysForbidden) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] publicApiServiceDeleteApiKeysForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysForbidden) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] publicApiServiceDeleteApiKeysForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *PublicAPIServiceDeleteAPIKeysForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceDeleteAPIKeysNotFound creates a PublicAPIServiceDeleteAPIKeysNotFound with default headers values
func NewPublicAPIServiceDeleteAPIKeysNotFound() *PublicAPIServiceDeleteAPIKeysNotFound {
	return &PublicAPIServiceDeleteAPIKeysNotFound{}
}

/*
PublicAPIServiceDeleteAPIKeysNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type PublicAPIServiceDeleteAPIKeysNotFound struct {
	Payload string
}

// IsSuccess returns true when this public Api service delete Api keys not found response has a 2xx status code
func (o *PublicAPIServiceDeleteAPIKeysNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service delete Api keys not found response has a 3xx status code
func (o *PublicAPIServiceDeleteAPIKeysNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service delete Api keys not found response has a 4xx status code
func (o *PublicAPIServiceDeleteAPIKeysNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service delete Api keys not found response has a 5xx status code
func (o *PublicAPIServiceDeleteAPIKeysNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service delete Api keys not found response a status code equal to that given
func (o *PublicAPIServiceDeleteAPIKeysNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the public Api service delete Api keys not found response
func (o *PublicAPIServiceDeleteAPIKeysNotFound) Code() int {
	return 404
}

func (o *PublicAPIServiceDeleteAPIKeysNotFound) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] publicApiServiceDeleteApiKeysNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysNotFound) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] publicApiServiceDeleteApiKeysNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysNotFound) GetPayload() string {
	return o.Payload
}

func (o *PublicAPIServiceDeleteAPIKeysNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceDeleteAPIKeysDefault creates a PublicAPIServiceDeleteAPIKeysDefault with default headers values
func NewPublicAPIServiceDeleteAPIKeysDefault(code int) *PublicAPIServiceDeleteAPIKeysDefault {
	return &PublicAPIServiceDeleteAPIKeysDefault{
		_statusCode: code,
	}
}

/*
PublicAPIServiceDeleteAPIKeysDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PublicAPIServiceDeleteAPIKeysDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this public Api service delete Api keys default response has a 2xx status code
func (o *PublicAPIServiceDeleteAPIKeysDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this public Api service delete Api keys default response has a 3xx status code
func (o *PublicAPIServiceDeleteAPIKeysDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this public Api service delete Api keys default response has a 4xx status code
func (o *PublicAPIServiceDeleteAPIKeysDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this public Api service delete Api keys default response has a 5xx status code
func (o *PublicAPIServiceDeleteAPIKeysDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this public Api service delete Api keys default response a status code equal to that given
func (o *PublicAPIServiceDeleteAPIKeysDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the public Api service delete Api keys default response
func (o *PublicAPIServiceDeleteAPIKeysDefault) Code() int {
	return o._statusCode
}

func (o *PublicAPIServiceDeleteAPIKeysDefault) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] PublicApiService_DeleteApiKeys default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysDefault) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_api_keys][%d] PublicApiService_DeleteApiKeys default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceDeleteAPIKeysDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PublicAPIServiceDeleteAPIKeysDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
