// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/api/models"
)

// NewPublicAPIServiceGetWhoamiParams creates a new PublicAPIServiceGetWhoamiParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceGetWhoamiParams() *PublicAPIServiceGetWhoamiParams {
	return &PublicAPIServiceGetWhoamiParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceGetWhoamiParamsWithTimeout creates a new PublicAPIServiceGetWhoamiParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceGetWhoamiParamsWithTimeout(timeout time.Duration) *PublicAPIServiceGetWhoamiParams {
	return &PublicAPIServiceGetWhoamiParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceGetWhoamiParamsWithContext creates a new PublicAPIServiceGetWhoamiParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceGetWhoamiParamsWithContext(ctx context.Context) *PublicAPIServiceGetWhoamiParams {
	return &PublicAPIServiceGetWhoamiParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceGetWhoamiParamsWithHTTPClient creates a new PublicAPIServiceGetWhoamiParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceGetWhoamiParamsWithHTTPClient(client *http.Client) *PublicAPIServiceGetWhoamiParams {
	return &PublicAPIServiceGetWhoamiParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceGetWhoamiParams contains all the parameters to send to the API endpoint

	for the public Api service get whoami operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceGetWhoamiParams struct {

	// Body.
	Body *models.V1GetWhoamiRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service get whoami params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetWhoamiParams) WithDefaults() *PublicAPIServiceGetWhoamiParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service get whoami params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetWhoamiParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) WithTimeout(timeout time.Duration) *PublicAPIServiceGetWhoamiParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) WithContext(ctx context.Context) *PublicAPIServiceGetWhoamiParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) WithHTTPClient(client *http.Client) *PublicAPIServiceGetWhoamiParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) WithBody(body *models.V1GetWhoamiRequest) *PublicAPIServiceGetWhoamiParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service get whoami params
func (o *PublicAPIServiceGetWhoamiParams) SetBody(body *models.V1GetWhoamiRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceGetWhoamiParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
