package pkg

import (
	"github.com/rotisserie/eris"
	"github.com/spf13/cobra"

	"github.com/tkhq/go-sdk/pkg/api/client/private_keys"
	"github.com/tkhq/go-sdk/pkg/api/models"
	"github.com/tkhq/go-sdk/pkg/util"
)

var (
	privateKeysCreateAddressFormats []string
	privateKeysCreateCurve          string
	privateKeysCreateName           string
	privateKeysCreateTags           []string
	privateKeyNameOrID              string
	privateKeyUserID                string
	privateKeyTargetPublicKeyPath   string
	privateKeyExportBundlePath      string
	privateKeyImportBundlePath      string
	privateKeyEncryptedBundlePath   string
)

func init() {
	privateKeysCreateCmd.Flags().StringSliceVar(&privateKeysCreateAddressFormats, "address-format", nil, "address format(s) for private key.  For a list of formats, use 'turnkey address-formats list'.")
	privateKeysCreateCmd.Flags().StringVar(&privateKeysCreateCurve, "curve", "", "curve to use for the generation of the private key.  For a list of available curves, use 'turnkey curves list'.")
	privateKeysCreateCmd.Flags().StringVar(&privateKeysCreateName, "name", "", "name to be applied to the private key")
	privateKeysCreateCmd.Flags().StringSliceVar(&privateKeysCreateTags, "tag", make([]string, 0), "tag(s) to be applied to the private key")

	privateKeyExportCmd.Flags().StringVar(&privateKeyNameOrID, "id", "", "name or ID of private key to export.")
	privateKeyExportCmd.Flags().StringVar(&privateKeyTargetPublicKeyPath, "target-public-key-path", "/target_public_key.txt", "filepath to read the target public key generated by `generate encryption-key`.")
	privateKeyExportCmd.Flags().StringVar(&privateKeyExportBundlePath, "export-bundle-path", "/export_bundle.txt", "filepath to write the export bundle to.")

	privateKeyInitImportCmd.Flags().StringVar(&privateKeyUserID, "name", "", "ID of user to importing the private key")
	privateKeyInitImportCmd.Flags().StringVar(&privateKeyImportBundlePath, "import-bundle-path", "/import_bundle.txt", "filepath to write the import bundle to.")

	privateKeyImportCmd.Flags().StringVar(&privateKeyUserID, "name", "", "ID of user to importing the private key")
	privateKeyImportCmd.Flags().StringVar(&privateKeysCreateName, "name", "", "name to be applied to the private key.")
	privateKeyImportCmd.Flags().StringVar(&privateKeyEncryptedBundlePath, "encrypted-bundle-path", "/encrypted_bundle.txt", "filepath to read the encrypted bundle from.")

	privateKeysCmd.AddCommand(privateKeysCreateCmd)
	privateKeysCmd.AddCommand(privateKeysListCmd)

	rootCmd.AddCommand(privateKeysCmd)
}

var privateKeysCmd = &cobra.Command{
	Use:   "private-keys",
	Short: "Interact with private keys",
	PersistentPreRun: func(cmd *cobra.Command, args []string) {
		basicSetup(cmd)
		LoadKeypair("")
		LoadClient()
	},
	Aliases: []string{"pk"},
}

var privateKeysCreateCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new private key",
	PreRun: func(cmd *cobra.Command, args []string) {
		if len(privateKeysCreateAddressFormats) < 1 {
			OutputError(eris.New("must specify at least one address format"))
		}

		if privateKeysCreateCurve == "" {
			OutputError(eris.New("curve cannot be empty"))
		}

		if privateKeysCreateName == "" {
			OutputError(eris.New("name for private key must be specified"))
		}
	},
	Run: func(cmd *cobra.Command, args []string) {
		curve := models.Curve(privateKeysCreateCurve)

		if curve == Help {
			Output(models.CurveEnum)
			return
		}

		addressFormats := make([]models.AddressFormat, len(privateKeysCreateAddressFormats))

		for n, f := range privateKeysCreateAddressFormats {
			if f == Help {
				Output(models.AddressFormatEnum)
				return
			}

			addressFormats[n] = models.AddressFormat(f)
		}

		activity := string(models.ActivityTypeCreatePrivateKeysV2)

		params := private_keys.NewCreatePrivateKeysParams()
		params.SetBody(&models.CreatePrivateKeysRequest{
			OrganizationID: &Organization,
			Parameters: &models.CreatePrivateKeysIntentV2{
				PrivateKeys: []*models.PrivateKeyParams{
					{
						AddressFormats: addressFormats,
						Curve:          &curve,
						PrivateKeyName: &privateKeysCreateName,
						PrivateKeyTags: privateKeysCreateTags,
					},
				},
			},
			TimestampMs: util.RequestTimestamp(),
			Type:        &activity,
		})

		if err := params.Body.Validate(nil); err != nil {
			OutputError(eris.Wrap(err, "request validation failed"))
		}

		resp, err := APIClient.V0().PrivateKeys.CreatePrivateKeys(params, APIClient.Authenticator)
		if err != nil {
			OutputError(eris.Wrap(err, "request failed"))
		}

		if !resp.IsSuccess() {
			OutputError(eris.Errorf("failed to create private key: %s", resp.Error()))
		}

		Output(resp.Payload)
	},
}

var privateKeysListCmd = &cobra.Command{
	Use:   "list",
	Short: "Return private keys for the organization",
	Run: func(cmd *cobra.Command, args []string) {
		params := private_keys.NewGetPrivateKeysParams()

		params.SetBody(&models.GetPrivateKeysRequest{
			OrganizationID: &Organization,
		})

		if err := params.Body.Validate(nil); err != nil {
			OutputError(eris.Wrap(err, "request validation failed"))
		}

		resp, err := APIClient.V0().PrivateKeys.GetPrivateKeys(params, APIClient.Authenticator)
		if err != nil {
			OutputError(eris.Wrap(err, "request failed"))
		}

		if !resp.IsSuccess() {
			OutputError(eris.Errorf("failed to list private keys: %s", resp.Error()))
		}

		Output(resp.Payload)
	},
}

var privateKeyExportCmd = &cobra.Command{
	Use:   "export",
	Short: "Export a private key",
	PreRun: func(cmd *cobra.Command, args []string) {
		if privateKeyNameOrID == "" {
			OutputError(eris.New("ID for private key must be specified"))
		}
	},
	Run: func(cmd *cobra.Command, args []string) {
		privateKey, err := lookupPrivateKey(privateKeyNameOrID)
		if err != nil {
			OutputError(eris.Wrap(err, "failed to lookup private key"))
		}

		targetPublicKey, err := ReadFile(privateKeyTargetPublicKeyPath)
		if err != nil {
			OutputError(err)
		}

		activity := string(models.ActivityTypeExportPrivateKey)

		params := private_keys.NewExportPrivateKeyParams()
		params.SetBody(&models.ExportPrivateKeyRequest{
			OrganizationID: &Organization,
			Parameters: &models.ExportPrivateKeyIntent{
				PrivateKeyID:    privateKey.PrivateKeyID,
				TargetPublicKey: &targetPublicKey,
			},
			TimestampMs: util.RequestTimestamp(),
			Type:        &activity,
		})

		if err := params.Body.Validate(nil); err != nil {
			OutputError(eris.Wrap(err, "request validation failed"))
		}

		resp, err := APIClient.V0().PrivateKeys.ExportPrivateKey(params, APIClient.Authenticator)
		if err != nil {
			OutputError(eris.Wrap(err, "request failed"))
		}

		if !resp.IsSuccess() {
			OutputError(eris.Errorf("failed to export private key: %s", resp.Error()))
		}

		exportBundle := resp.Payload.Activity.Result.ExportPrivateKeyResult.ExportBundle
		err = WriteFile(*exportBundle, privateKeyExportBundlePath)
		if err != nil {
			OutputError(eris.Wrap(err, "failed to write export bundle to file"))
		}

		exportedPrivateKeyID := resp.Payload.Activity.Result.ExportPrivateKeyResult.PrivateKeyID
		Output(exportedPrivateKeyID)
	},
}

var privateKeyInitImportCmd = &cobra.Command{
	Use:   "init-import",
	Short: "Initialize private key import",
	PreRun: func(cmd *cobra.Command, args []string) {
		if privateKeyUserID == "" {
			OutputError(eris.New("ID for user importing private key must be specified"))
		}
	},
	Run: func(cmd *cobra.Command, args []string) {
		activity := string(models.ActivityTypeInitImportPrivateKey)

		params := private_keys.NewInitImportPrivateKeyParams()
		params.SetBody(&models.InitImportPrivateKeyRequest{
			OrganizationID: &Organization,
			Parameters: &models.InitImportPrivateKeyIntent{
				UserID: &privateKeyUserID,
			},
			TimestampMs: util.RequestTimestamp(),
			Type:        &activity,
		})

		if err := params.Body.Validate(nil); err != nil {
			OutputError(eris.Wrap(err, "request validation failed"))
		}

		resp, err := APIClient.V0().PrivateKeys.InitImportPrivateKey(params, APIClient.Authenticator)
		if err != nil {
			OutputError(eris.Wrap(err, "request failed"))
		}

		if !resp.IsSuccess() {
			OutputError(eris.Errorf("failed to initialize private key import: %s", resp.Error()))
		}

		importBundle := resp.Payload.Activity.Result.InitImportPrivateKeyResult.ImportBundle
		err = WriteFile(*importBundle, privateKeyImportBundlePath)
		if err != nil {
			OutputError(eris.Wrap(err, "failed to write import bundle to file"))
		}
	},
}

var privateKeyImportCmd = &cobra.Command{
	Use:   "import",
	Short: "Import a private key",
	PreRun: func(cmd *cobra.Command, args []string) {
		if len(privateKeysCreateAddressFormats) < 1 {
			OutputError(eris.New("must specify at least one address format"))
		}

		if privateKeysCreateCurve == "" {
			OutputError(eris.New("curve cannot be empty"))
		}

		if privateKeysCreateName == "" {
			OutputError(eris.New("name for private key must be specified"))
		}
	},
	Run: func(cmd *cobra.Command, args []string) {
		encryptedBundle, err := ReadFile(privateKeyEncryptedBundlePath)
		if err != nil {
			OutputError(err)
		}

		curve := models.Curve(privateKeysCreateCurve)

		if curve == Help {
			Output(models.CurveEnum)
			return
		}

		addressFormats := make([]models.AddressFormat, len(privateKeysCreateAddressFormats))

		for n, f := range privateKeysCreateAddressFormats {
			if f == Help {
				Output(models.AddressFormatEnum)
				return
			}

			addressFormats[n] = models.AddressFormat(f)
		}

		activity := string(models.ActivityTypeImportPrivateKey)

		params := private_keys.NewImportPrivateKeyParams()
		params.SetBody(&models.ImportPrivateKeyRequest{
			OrganizationID: &Organization,
			Parameters: &models.ImportPrivateKeyIntent{
				UserID:          &privateKeyUserID,
				PrivateKeyName:  &privateKeysCreateName,
				EncryptedBundle: &encryptedBundle,
				Curve:           &curve,
				AddressFormats:  addressFormats,
			},
			TimestampMs: util.RequestTimestamp(),
			Type:        &activity,
		})

		if err := params.Body.Validate(nil); err != nil {
			OutputError(eris.Wrap(err, "request validation failed"))
		}

		resp, err := APIClient.V0().PrivateKeys.ImportPrivateKey(params, APIClient.Authenticator)
		if err != nil {
			OutputError(eris.Wrap(err, "request failed"))
		}

		if !resp.IsSuccess() {
			OutputError(eris.Errorf("failed to import private key: %s", resp.Error()))
		}

		Output(resp.Payload)
	},
}

func lookupPrivateKey(nameOrID string) (*models.PrivateKey, error) {
	params := private_keys.NewGetPrivateKeysParams()

	params.SetBody(&models.GetPrivateKeysRequest{
		OrganizationID: &Organization,
	})

	if err := params.Body.Validate(nil); err != nil {
		OutputError(eris.Wrap(err, "request validation failed"))
	}

	resp, err := APIClient.V0().PrivateKeys.GetPrivateKeys(params, APIClient.Authenticator)
	if err != nil {
		OutputError(eris.Wrap(err, "request failed"))
	}

	if !resp.IsSuccess() {
		OutputError(eris.Errorf("failed to list private keys: %s", resp.Error()))
	}

	for _, privateKey := range resp.Payload.PrivateKeys {
		if *privateKey.PrivateKeyName == nameOrID || *privateKey.PrivateKeyID == nameOrID {
			return privateKey, nil
		}
	}

	return nil, eris.Errorf("private key %q not found in list of private keys", nameOrID)
}
