// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/src/api/models"
)

// NewPublicAPIServiceCreatePolicyParams creates a new PublicAPIServiceCreatePolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceCreatePolicyParams() *PublicAPIServiceCreatePolicyParams {
	return &PublicAPIServiceCreatePolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceCreatePolicyParamsWithTimeout creates a new PublicAPIServiceCreatePolicyParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceCreatePolicyParamsWithTimeout(timeout time.Duration) *PublicAPIServiceCreatePolicyParams {
	return &PublicAPIServiceCreatePolicyParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceCreatePolicyParamsWithContext creates a new PublicAPIServiceCreatePolicyParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceCreatePolicyParamsWithContext(ctx context.Context) *PublicAPIServiceCreatePolicyParams {
	return &PublicAPIServiceCreatePolicyParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceCreatePolicyParamsWithHTTPClient creates a new PublicAPIServiceCreatePolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceCreatePolicyParamsWithHTTPClient(client *http.Client) *PublicAPIServiceCreatePolicyParams {
	return &PublicAPIServiceCreatePolicyParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceCreatePolicyParams contains all the parameters to send to the API endpoint

	for the public Api service create policy operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceCreatePolicyParams struct {

	// Body.
	Body *models.V1CreatePolicyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service create policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceCreatePolicyParams) WithDefaults() *PublicAPIServiceCreatePolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service create policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceCreatePolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) WithTimeout(timeout time.Duration) *PublicAPIServiceCreatePolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) WithContext(ctx context.Context) *PublicAPIServiceCreatePolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) WithHTTPClient(client *http.Client) *PublicAPIServiceCreatePolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) WithBody(body *models.V1CreatePolicyRequest) *PublicAPIServiceCreatePolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service create policy params
func (o *PublicAPIServiceCreatePolicyParams) SetBody(body *models.V1CreatePolicyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceCreatePolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
