// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/src/api/models"
)

// PublicAPIServiceGetPolicyReader is a Reader for the PublicAPIServiceGetPolicy structure.
type PublicAPIServiceGetPolicyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicAPIServiceGetPolicyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicAPIServiceGetPolicyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPublicAPIServiceGetPolicyForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPublicAPIServiceGetPolicyNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPublicAPIServiceGetPolicyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPublicAPIServiceGetPolicyOK creates a PublicAPIServiceGetPolicyOK with default headers values
func NewPublicAPIServiceGetPolicyOK() *PublicAPIServiceGetPolicyOK {
	return &PublicAPIServiceGetPolicyOK{}
}

/*
PublicAPIServiceGetPolicyOK describes a response with status code 200, with default header values.

A successful response.
*/
type PublicAPIServiceGetPolicyOK struct {
	Payload *models.V1GetPolicyResponse
}

// IsSuccess returns true when this public Api service get policy o k response has a 2xx status code
func (o *PublicAPIServiceGetPolicyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this public Api service get policy o k response has a 3xx status code
func (o *PublicAPIServiceGetPolicyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service get policy o k response has a 4xx status code
func (o *PublicAPIServiceGetPolicyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this public Api service get policy o k response has a 5xx status code
func (o *PublicAPIServiceGetPolicyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service get policy o k response a status code equal to that given
func (o *PublicAPIServiceGetPolicyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the public Api service get policy o k response
func (o *PublicAPIServiceGetPolicyOK) Code() int {
	return 200
}

func (o *PublicAPIServiceGetPolicyOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] publicApiServiceGetPolicyOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceGetPolicyOK) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] publicApiServiceGetPolicyOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceGetPolicyOK) GetPayload() *models.V1GetPolicyResponse {
	return o.Payload
}

func (o *PublicAPIServiceGetPolicyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1GetPolicyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceGetPolicyForbidden creates a PublicAPIServiceGetPolicyForbidden with default headers values
func NewPublicAPIServiceGetPolicyForbidden() *PublicAPIServiceGetPolicyForbidden {
	return &PublicAPIServiceGetPolicyForbidden{}
}

/*
PublicAPIServiceGetPolicyForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type PublicAPIServiceGetPolicyForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this public Api service get policy forbidden response has a 2xx status code
func (o *PublicAPIServiceGetPolicyForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service get policy forbidden response has a 3xx status code
func (o *PublicAPIServiceGetPolicyForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service get policy forbidden response has a 4xx status code
func (o *PublicAPIServiceGetPolicyForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service get policy forbidden response has a 5xx status code
func (o *PublicAPIServiceGetPolicyForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service get policy forbidden response a status code equal to that given
func (o *PublicAPIServiceGetPolicyForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the public Api service get policy forbidden response
func (o *PublicAPIServiceGetPolicyForbidden) Code() int {
	return 403
}

func (o *PublicAPIServiceGetPolicyForbidden) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] publicApiServiceGetPolicyForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceGetPolicyForbidden) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] publicApiServiceGetPolicyForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceGetPolicyForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *PublicAPIServiceGetPolicyForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceGetPolicyNotFound creates a PublicAPIServiceGetPolicyNotFound with default headers values
func NewPublicAPIServiceGetPolicyNotFound() *PublicAPIServiceGetPolicyNotFound {
	return &PublicAPIServiceGetPolicyNotFound{}
}

/*
PublicAPIServiceGetPolicyNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type PublicAPIServiceGetPolicyNotFound struct {
	Payload string
}

// IsSuccess returns true when this public Api service get policy not found response has a 2xx status code
func (o *PublicAPIServiceGetPolicyNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service get policy not found response has a 3xx status code
func (o *PublicAPIServiceGetPolicyNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service get policy not found response has a 4xx status code
func (o *PublicAPIServiceGetPolicyNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service get policy not found response has a 5xx status code
func (o *PublicAPIServiceGetPolicyNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service get policy not found response a status code equal to that given
func (o *PublicAPIServiceGetPolicyNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the public Api service get policy not found response
func (o *PublicAPIServiceGetPolicyNotFound) Code() int {
	return 404
}

func (o *PublicAPIServiceGetPolicyNotFound) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] publicApiServiceGetPolicyNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceGetPolicyNotFound) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] publicApiServiceGetPolicyNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceGetPolicyNotFound) GetPayload() string {
	return o.Payload
}

func (o *PublicAPIServiceGetPolicyNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceGetPolicyDefault creates a PublicAPIServiceGetPolicyDefault with default headers values
func NewPublicAPIServiceGetPolicyDefault(code int) *PublicAPIServiceGetPolicyDefault {
	return &PublicAPIServiceGetPolicyDefault{
		_statusCode: code,
	}
}

/*
PublicAPIServiceGetPolicyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PublicAPIServiceGetPolicyDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this public Api service get policy default response has a 2xx status code
func (o *PublicAPIServiceGetPolicyDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this public Api service get policy default response has a 3xx status code
func (o *PublicAPIServiceGetPolicyDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this public Api service get policy default response has a 4xx status code
func (o *PublicAPIServiceGetPolicyDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this public Api service get policy default response has a 5xx status code
func (o *PublicAPIServiceGetPolicyDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this public Api service get policy default response a status code equal to that given
func (o *PublicAPIServiceGetPolicyDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the public Api service get policy default response
func (o *PublicAPIServiceGetPolicyDefault) Code() int {
	return o._statusCode
}

func (o *PublicAPIServiceGetPolicyDefault) Error() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] PublicApiService_GetPolicy default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceGetPolicyDefault) String() string {
	return fmt.Sprintf("[POST /public/v1/query/get_policy][%d] PublicApiService_GetPolicy default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceGetPolicyDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PublicAPIServiceGetPolicyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
