// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/api/models"
)

// NewPublicAPIServiceGetPolicyParams creates a new PublicAPIServiceGetPolicyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceGetPolicyParams() *PublicAPIServiceGetPolicyParams {
	return &PublicAPIServiceGetPolicyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceGetPolicyParamsWithTimeout creates a new PublicAPIServiceGetPolicyParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceGetPolicyParamsWithTimeout(timeout time.Duration) *PublicAPIServiceGetPolicyParams {
	return &PublicAPIServiceGetPolicyParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceGetPolicyParamsWithContext creates a new PublicAPIServiceGetPolicyParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceGetPolicyParamsWithContext(ctx context.Context) *PublicAPIServiceGetPolicyParams {
	return &PublicAPIServiceGetPolicyParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceGetPolicyParamsWithHTTPClient creates a new PublicAPIServiceGetPolicyParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceGetPolicyParamsWithHTTPClient(client *http.Client) *PublicAPIServiceGetPolicyParams {
	return &PublicAPIServiceGetPolicyParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceGetPolicyParams contains all the parameters to send to the API endpoint

	for the public Api service get policy operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceGetPolicyParams struct {

	// Body.
	Body *models.V1GetPolicyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service get policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetPolicyParams) WithDefaults() *PublicAPIServiceGetPolicyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service get policy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetPolicyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) WithTimeout(timeout time.Duration) *PublicAPIServiceGetPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) WithContext(ctx context.Context) *PublicAPIServiceGetPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) WithHTTPClient(client *http.Client) *PublicAPIServiceGetPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) WithBody(body *models.V1GetPolicyRequest) *PublicAPIServiceGetPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service get policy params
func (o *PublicAPIServiceGetPolicyParams) SetBody(body *models.V1GetPolicyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceGetPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
