// Code generated by go-swagger; DO NOT EDIT.

package organizations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/src/api/models"
)

// PublicAPIServiceDeleteInvitationReader is a Reader for the PublicAPIServiceDeleteInvitation structure.
type PublicAPIServiceDeleteInvitationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicAPIServiceDeleteInvitationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicAPIServiceDeleteInvitationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPublicAPIServiceDeleteInvitationForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPublicAPIServiceDeleteInvitationNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPublicAPIServiceDeleteInvitationDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPublicAPIServiceDeleteInvitationOK creates a PublicAPIServiceDeleteInvitationOK with default headers values
func NewPublicAPIServiceDeleteInvitationOK() *PublicAPIServiceDeleteInvitationOK {
	return &PublicAPIServiceDeleteInvitationOK{}
}

/*
PublicAPIServiceDeleteInvitationOK describes a response with status code 200, with default header values.

A successful response.
*/
type PublicAPIServiceDeleteInvitationOK struct {
	Payload *models.V1ActivityResponse
}

// IsSuccess returns true when this public Api service delete invitation o k response has a 2xx status code
func (o *PublicAPIServiceDeleteInvitationOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this public Api service delete invitation o k response has a 3xx status code
func (o *PublicAPIServiceDeleteInvitationOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service delete invitation o k response has a 4xx status code
func (o *PublicAPIServiceDeleteInvitationOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this public Api service delete invitation o k response has a 5xx status code
func (o *PublicAPIServiceDeleteInvitationOK) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service delete invitation o k response a status code equal to that given
func (o *PublicAPIServiceDeleteInvitationOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the public Api service delete invitation o k response
func (o *PublicAPIServiceDeleteInvitationOK) Code() int {
	return 200
}

func (o *PublicAPIServiceDeleteInvitationOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] publicApiServiceDeleteInvitationOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] publicApiServiceDeleteInvitationOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationOK) GetPayload() *models.V1ActivityResponse {
	return o.Payload
}

func (o *PublicAPIServiceDeleteInvitationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceDeleteInvitationForbidden creates a PublicAPIServiceDeleteInvitationForbidden with default headers values
func NewPublicAPIServiceDeleteInvitationForbidden() *PublicAPIServiceDeleteInvitationForbidden {
	return &PublicAPIServiceDeleteInvitationForbidden{}
}

/*
PublicAPIServiceDeleteInvitationForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type PublicAPIServiceDeleteInvitationForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this public Api service delete invitation forbidden response has a 2xx status code
func (o *PublicAPIServiceDeleteInvitationForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service delete invitation forbidden response has a 3xx status code
func (o *PublicAPIServiceDeleteInvitationForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service delete invitation forbidden response has a 4xx status code
func (o *PublicAPIServiceDeleteInvitationForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service delete invitation forbidden response has a 5xx status code
func (o *PublicAPIServiceDeleteInvitationForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service delete invitation forbidden response a status code equal to that given
func (o *PublicAPIServiceDeleteInvitationForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the public Api service delete invitation forbidden response
func (o *PublicAPIServiceDeleteInvitationForbidden) Code() int {
	return 403
}

func (o *PublicAPIServiceDeleteInvitationForbidden) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] publicApiServiceDeleteInvitationForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationForbidden) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] publicApiServiceDeleteInvitationForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *PublicAPIServiceDeleteInvitationForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceDeleteInvitationNotFound creates a PublicAPIServiceDeleteInvitationNotFound with default headers values
func NewPublicAPIServiceDeleteInvitationNotFound() *PublicAPIServiceDeleteInvitationNotFound {
	return &PublicAPIServiceDeleteInvitationNotFound{}
}

/*
PublicAPIServiceDeleteInvitationNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type PublicAPIServiceDeleteInvitationNotFound struct {
	Payload string
}

// IsSuccess returns true when this public Api service delete invitation not found response has a 2xx status code
func (o *PublicAPIServiceDeleteInvitationNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service delete invitation not found response has a 3xx status code
func (o *PublicAPIServiceDeleteInvitationNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service delete invitation not found response has a 4xx status code
func (o *PublicAPIServiceDeleteInvitationNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service delete invitation not found response has a 5xx status code
func (o *PublicAPIServiceDeleteInvitationNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service delete invitation not found response a status code equal to that given
func (o *PublicAPIServiceDeleteInvitationNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the public Api service delete invitation not found response
func (o *PublicAPIServiceDeleteInvitationNotFound) Code() int {
	return 404
}

func (o *PublicAPIServiceDeleteInvitationNotFound) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] publicApiServiceDeleteInvitationNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationNotFound) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] publicApiServiceDeleteInvitationNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationNotFound) GetPayload() string {
	return o.Payload
}

func (o *PublicAPIServiceDeleteInvitationNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceDeleteInvitationDefault creates a PublicAPIServiceDeleteInvitationDefault with default headers values
func NewPublicAPIServiceDeleteInvitationDefault(code int) *PublicAPIServiceDeleteInvitationDefault {
	return &PublicAPIServiceDeleteInvitationDefault{
		_statusCode: code,
	}
}

/*
PublicAPIServiceDeleteInvitationDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PublicAPIServiceDeleteInvitationDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this public Api service delete invitation default response has a 2xx status code
func (o *PublicAPIServiceDeleteInvitationDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this public Api service delete invitation default response has a 3xx status code
func (o *PublicAPIServiceDeleteInvitationDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this public Api service delete invitation default response has a 4xx status code
func (o *PublicAPIServiceDeleteInvitationDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this public Api service delete invitation default response has a 5xx status code
func (o *PublicAPIServiceDeleteInvitationDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this public Api service delete invitation default response a status code equal to that given
func (o *PublicAPIServiceDeleteInvitationDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the public Api service delete invitation default response
func (o *PublicAPIServiceDeleteInvitationDefault) Code() int {
	return o._statusCode
}

func (o *PublicAPIServiceDeleteInvitationDefault) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] PublicApiService_DeleteInvitation default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationDefault) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/delete_invitations][%d] PublicApiService_DeleteInvitation default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceDeleteInvitationDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PublicAPIServiceDeleteInvitationDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
