// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Immutableactivityv1Effect immutableactivityv1 effect
//
// swagger:model immutableactivityv1Effect
type Immutableactivityv1Effect string

func NewImmutableactivityv1Effect(value Immutableactivityv1Effect) *Immutableactivityv1Effect {
	return &value
}

// Pointer returns a pointer to a freshly-allocated Immutableactivityv1Effect.
func (m Immutableactivityv1Effect) Pointer() *Immutableactivityv1Effect {
	return &m
}

const (

	// Immutableactivityv1EffectEFFECTALLOW captures enum value "EFFECT_ALLOW"
	Immutableactivityv1EffectEFFECTALLOW Immutableactivityv1Effect = "EFFECT_ALLOW"

	// Immutableactivityv1EffectEFFECTDENY captures enum value "EFFECT_DENY"
	Immutableactivityv1EffectEFFECTDENY Immutableactivityv1Effect = "EFFECT_DENY"
)

// for schema
var immutableactivityv1EffectEnum []interface{}

func init() {
	var res []Immutableactivityv1Effect
	if err := json.Unmarshal([]byte(`["EFFECT_ALLOW","EFFECT_DENY"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		immutableactivityv1EffectEnum = append(immutableactivityv1EffectEnum, v)
	}
}

func (m Immutableactivityv1Effect) validateImmutableactivityv1EffectEnum(path, location string, value Immutableactivityv1Effect) error {
	if err := validate.EnumCase(path, location, value, immutableactivityv1EffectEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this immutableactivityv1 effect
func (m Immutableactivityv1Effect) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateImmutableactivityv1EffectEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this immutableactivityv1 effect based on context it is used
func (m Immutableactivityv1Effect) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
