// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1ApproveActivityIntent v1 approve activity intent
//
// swagger:model v1ApproveActivityIntent
type V1ApproveActivityIntent struct {

	// @inject_tag: validate:"required"
	//
	// An artifact verifying a User's action.
	// Required: true
	Fingerprint *string `json:"fingerprint"`
}

// Validate validates this v1 approve activity intent
func (m *V1ApproveActivityIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFingerprint(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1ApproveActivityIntent) validateFingerprint(formats strfmt.Registry) error {

	if err := validate.Required("fingerprint", "body", m.Fingerprint); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 approve activity intent based on context it is used
func (m *V1ApproveActivityIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1ApproveActivityIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1ApproveActivityIntent) UnmarshalBinary(b []byte) error {
	var res V1ApproveActivityIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
