// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1DeleteAuthenticatorsIntent v1 delete authenticators intent
//
// swagger:model v1DeleteAuthenticatorsIntent
type V1DeleteAuthenticatorsIntent struct {

	// @inject_tag: validate:"required,div,required,uuid"
	//
	// A list of Authenticator IDs.
	// Required: true
	AuthenticatorIds []string `json:"authenticatorIds"`

	// @inject_tag: validate:"required,uuid"
	//
	// Unique identifier for a given User.
	// Required: true
	UserID *string `json:"userId"`
}

// Validate validates this v1 delete authenticators intent
func (m *V1DeleteAuthenticatorsIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthenticatorIds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1DeleteAuthenticatorsIntent) validateAuthenticatorIds(formats strfmt.Registry) error {

	if err := validate.Required("authenticatorIds", "body", m.AuthenticatorIds); err != nil {
		return err
	}

	return nil
}

func (m *V1DeleteAuthenticatorsIntent) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("userId", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 delete authenticators intent based on context it is used
func (m *V1DeleteAuthenticatorsIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DeleteAuthenticatorsIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DeleteAuthenticatorsIntent) UnmarshalBinary(b []byte) error {
	var res V1DeleteAuthenticatorsIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
