// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1Invitation v1 invitation
//
// swagger:model v1Invitation
type V1Invitation struct {

	// access type
	// Required: true
	AccessType *Externaldatav1AccessType `json:"accessType"`

	// created at
	// Required: true
	CreatedAt *V1Timestamp `json:"createdAt"`

	// Unique identifier for a given Invitation object.
	// Required: true
	InvitationID *string `json:"invitationId"`

	// The email address of the intended Invitation recipient.
	// Required: true
	ReceiverEmail *string `json:"receiverEmail"`

	// The name of the intended Invitation recipient.
	// Required: true
	ReceiverUserName *string `json:"receiverUserName"`

	// A list of tags assigned to the Invitation recipient.
	// Required: true
	ReceiverUserTags []string `json:"receiverUserTags"`

	// Unique identifier for the Sender of an Invitation.
	// Required: true
	SenderUserID *string `json:"senderUserId"`

	// status
	// Required: true
	Status *V1InvitationStatus `json:"status"`

	// updated at
	// Required: true
	UpdatedAt *V1Timestamp `json:"updatedAt"`
}

// Validate validates this v1 invitation
func (m *V1Invitation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInvitationID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReceiverEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReceiverUserName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReceiverUserTags(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSenderUserID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Invitation) validateAccessType(formats strfmt.Registry) error {

	if err := validate.Required("accessType", "body", m.AccessType); err != nil {
		return err
	}

	if err := validate.Required("accessType", "body", m.AccessType); err != nil {
		return err
	}

	if m.AccessType != nil {
		if err := m.AccessType.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("accessType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("accessType")
			}
			return err
		}
	}

	return nil
}

func (m *V1Invitation) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("createdAt", "body", m.CreatedAt); err != nil {
		return err
	}

	if m.CreatedAt != nil {
		if err := m.CreatedAt.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

func (m *V1Invitation) validateInvitationID(formats strfmt.Registry) error {

	if err := validate.Required("invitationId", "body", m.InvitationID); err != nil {
		return err
	}

	return nil
}

func (m *V1Invitation) validateReceiverEmail(formats strfmt.Registry) error {

	if err := validate.Required("receiverEmail", "body", m.ReceiverEmail); err != nil {
		return err
	}

	return nil
}

func (m *V1Invitation) validateReceiverUserName(formats strfmt.Registry) error {

	if err := validate.Required("receiverUserName", "body", m.ReceiverUserName); err != nil {
		return err
	}

	return nil
}

func (m *V1Invitation) validateReceiverUserTags(formats strfmt.Registry) error {

	if err := validate.Required("receiverUserTags", "body", m.ReceiverUserTags); err != nil {
		return err
	}

	return nil
}

func (m *V1Invitation) validateSenderUserID(formats strfmt.Registry) error {

	if err := validate.Required("senderUserId", "body", m.SenderUserID); err != nil {
		return err
	}

	return nil
}

func (m *V1Invitation) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *V1Invitation) validateUpdatedAt(formats strfmt.Registry) error {

	if err := validate.Required("updatedAt", "body", m.UpdatedAt); err != nil {
		return err
	}

	if m.UpdatedAt != nil {
		if err := m.UpdatedAt.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updatedAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updatedAt")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this v1 invitation based on the context it is used
func (m *V1Invitation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccessType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedAt(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Invitation) contextValidateAccessType(ctx context.Context, formats strfmt.Registry) error {

	if m.AccessType != nil {
		if err := m.AccessType.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("accessType")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("accessType")
			}
			return err
		}
	}

	return nil
}

func (m *V1Invitation) contextValidateCreatedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.CreatedAt != nil {
		if err := m.CreatedAt.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createdAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("createdAt")
			}
			return err
		}
	}

	return nil
}

func (m *V1Invitation) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {
		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

func (m *V1Invitation) contextValidateUpdatedAt(ctx context.Context, formats strfmt.Registry) error {

	if m.UpdatedAt != nil {
		if err := m.UpdatedAt.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updatedAt")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updatedAt")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1Invitation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Invitation) UnmarshalBinary(b []byte) error {
	var res V1Invitation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
