// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1Timestamp v1 timestamp
//
// swagger:model v1Timestamp
type V1Timestamp struct {

	// nanos
	// Required: true
	Nanos *string `json:"nanos"`

	// seconds
	// Required: true
	Seconds *string `json:"seconds"`
}

// Validate validates this v1 timestamp
func (m *V1Timestamp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNanos(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeconds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1Timestamp) validateNanos(formats strfmt.Registry) error {

	if err := validate.Required("nanos", "body", m.Nanos); err != nil {
		return err
	}

	return nil
}

func (m *V1Timestamp) validateSeconds(formats strfmt.Registry) error {

	if err := validate.Required("seconds", "body", m.Seconds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 timestamp based on context it is used
func (m *V1Timestamp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1Timestamp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1Timestamp) UnmarshalBinary(b []byte) error {
	var res V1Timestamp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
