// Code generated by go-swagger; DO NOT EDIT.

package private_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/src/api/models"
)

// NewPublicAPIServiceCreatePrivateKeysParams creates a new PublicAPIServiceCreatePrivateKeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceCreatePrivateKeysParams() *PublicAPIServiceCreatePrivateKeysParams {
	return &PublicAPIServiceCreatePrivateKeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceCreatePrivateKeysParamsWithTimeout creates a new PublicAPIServiceCreatePrivateKeysParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceCreatePrivateKeysParamsWithTimeout(timeout time.Duration) *PublicAPIServiceCreatePrivateKeysParams {
	return &PublicAPIServiceCreatePrivateKeysParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceCreatePrivateKeysParamsWithContext creates a new PublicAPIServiceCreatePrivateKeysParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceCreatePrivateKeysParamsWithContext(ctx context.Context) *PublicAPIServiceCreatePrivateKeysParams {
	return &PublicAPIServiceCreatePrivateKeysParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceCreatePrivateKeysParamsWithHTTPClient creates a new PublicAPIServiceCreatePrivateKeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceCreatePrivateKeysParamsWithHTTPClient(client *http.Client) *PublicAPIServiceCreatePrivateKeysParams {
	return &PublicAPIServiceCreatePrivateKeysParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceCreatePrivateKeysParams contains all the parameters to send to the API endpoint

	for the public Api service create private keys operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceCreatePrivateKeysParams struct {

	// Body.
	Body *models.V1CreatePrivateKeysRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service create private keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceCreatePrivateKeysParams) WithDefaults() *PublicAPIServiceCreatePrivateKeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service create private keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceCreatePrivateKeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) WithTimeout(timeout time.Duration) *PublicAPIServiceCreatePrivateKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) WithContext(ctx context.Context) *PublicAPIServiceCreatePrivateKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) WithHTTPClient(client *http.Client) *PublicAPIServiceCreatePrivateKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) WithBody(body *models.V1CreatePrivateKeysRequest) *PublicAPIServiceCreatePrivateKeysParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service create private keys params
func (o *PublicAPIServiceCreatePrivateKeysParams) SetBody(body *models.V1CreatePrivateKeysRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceCreatePrivateKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
