// Code generated by go-swagger; DO NOT EDIT.

package private_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/src/api/models"
)

// NewPublicAPIServiceGetPrivateKeysParams creates a new PublicAPIServiceGetPrivateKeysParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPublicAPIServiceGetPrivateKeysParams() *PublicAPIServiceGetPrivateKeysParams {
	return &PublicAPIServiceGetPrivateKeysParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPublicAPIServiceGetPrivateKeysParamsWithTimeout creates a new PublicAPIServiceGetPrivateKeysParams object
// with the ability to set a timeout on a request.
func NewPublicAPIServiceGetPrivateKeysParamsWithTimeout(timeout time.Duration) *PublicAPIServiceGetPrivateKeysParams {
	return &PublicAPIServiceGetPrivateKeysParams{
		timeout: timeout,
	}
}

// NewPublicAPIServiceGetPrivateKeysParamsWithContext creates a new PublicAPIServiceGetPrivateKeysParams object
// with the ability to set a context for a request.
func NewPublicAPIServiceGetPrivateKeysParamsWithContext(ctx context.Context) *PublicAPIServiceGetPrivateKeysParams {
	return &PublicAPIServiceGetPrivateKeysParams{
		Context: ctx,
	}
}

// NewPublicAPIServiceGetPrivateKeysParamsWithHTTPClient creates a new PublicAPIServiceGetPrivateKeysParams object
// with the ability to set a custom HTTPClient for a request.
func NewPublicAPIServiceGetPrivateKeysParamsWithHTTPClient(client *http.Client) *PublicAPIServiceGetPrivateKeysParams {
	return &PublicAPIServiceGetPrivateKeysParams{
		HTTPClient: client,
	}
}

/*
PublicAPIServiceGetPrivateKeysParams contains all the parameters to send to the API endpoint

	for the public Api service get private keys operation.

	Typically these are written to a http.Request.
*/
type PublicAPIServiceGetPrivateKeysParams struct {

	// Body.
	Body *models.V1GetPrivateKeysRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the public Api service get private keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetPrivateKeysParams) WithDefaults() *PublicAPIServiceGetPrivateKeysParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the public Api service get private keys params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PublicAPIServiceGetPrivateKeysParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) WithTimeout(timeout time.Duration) *PublicAPIServiceGetPrivateKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) WithContext(ctx context.Context) *PublicAPIServiceGetPrivateKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) WithHTTPClient(client *http.Client) *PublicAPIServiceGetPrivateKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) WithBody(body *models.V1GetPrivateKeysRequest) *PublicAPIServiceGetPrivateKeysParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the public Api service get private keys params
func (o *PublicAPIServiceGetPrivateKeysParams) SetBody(body *models.V1GetPrivateKeysRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PublicAPIServiceGetPrivateKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
