// Code generated by go-swagger; DO NOT EDIT.

package private_keys

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/tkhq/tkcli/src/api/models"
)

// PublicAPIServiceCreatePrivateKeysReader is a Reader for the PublicAPIServiceCreatePrivateKeys structure.
type PublicAPIServiceCreatePrivateKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicAPIServiceCreatePrivateKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPublicAPIServiceCreatePrivateKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewPublicAPIServiceCreatePrivateKeysForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPublicAPIServiceCreatePrivateKeysNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewPublicAPIServiceCreatePrivateKeysDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPublicAPIServiceCreatePrivateKeysOK creates a PublicAPIServiceCreatePrivateKeysOK with default headers values
func NewPublicAPIServiceCreatePrivateKeysOK() *PublicAPIServiceCreatePrivateKeysOK {
	return &PublicAPIServiceCreatePrivateKeysOK{}
}

/*
PublicAPIServiceCreatePrivateKeysOK describes a response with status code 200, with default header values.

A successful response.
*/
type PublicAPIServiceCreatePrivateKeysOK struct {
	Payload *models.V1ActivityResponse
}

// IsSuccess returns true when this public Api service create private keys o k response has a 2xx status code
func (o *PublicAPIServiceCreatePrivateKeysOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this public Api service create private keys o k response has a 3xx status code
func (o *PublicAPIServiceCreatePrivateKeysOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service create private keys o k response has a 4xx status code
func (o *PublicAPIServiceCreatePrivateKeysOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this public Api service create private keys o k response has a 5xx status code
func (o *PublicAPIServiceCreatePrivateKeysOK) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service create private keys o k response a status code equal to that given
func (o *PublicAPIServiceCreatePrivateKeysOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the public Api service create private keys o k response
func (o *PublicAPIServiceCreatePrivateKeysOK) Code() int {
	return 200
}

func (o *PublicAPIServiceCreatePrivateKeysOK) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] publicApiServiceCreatePrivateKeysOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysOK) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] publicApiServiceCreatePrivateKeysOK  %+v", 200, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysOK) GetPayload() *models.V1ActivityResponse {
	return o.Payload
}

func (o *PublicAPIServiceCreatePrivateKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1ActivityResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceCreatePrivateKeysForbidden creates a PublicAPIServiceCreatePrivateKeysForbidden with default headers values
func NewPublicAPIServiceCreatePrivateKeysForbidden() *PublicAPIServiceCreatePrivateKeysForbidden {
	return &PublicAPIServiceCreatePrivateKeysForbidden{}
}

/*
PublicAPIServiceCreatePrivateKeysForbidden describes a response with status code 403, with default header values.

Returned when the user does not have permission to access the resource.
*/
type PublicAPIServiceCreatePrivateKeysForbidden struct {
	Payload interface{}
}

// IsSuccess returns true when this public Api service create private keys forbidden response has a 2xx status code
func (o *PublicAPIServiceCreatePrivateKeysForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service create private keys forbidden response has a 3xx status code
func (o *PublicAPIServiceCreatePrivateKeysForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service create private keys forbidden response has a 4xx status code
func (o *PublicAPIServiceCreatePrivateKeysForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service create private keys forbidden response has a 5xx status code
func (o *PublicAPIServiceCreatePrivateKeysForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service create private keys forbidden response a status code equal to that given
func (o *PublicAPIServiceCreatePrivateKeysForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the public Api service create private keys forbidden response
func (o *PublicAPIServiceCreatePrivateKeysForbidden) Code() int {
	return 403
}

func (o *PublicAPIServiceCreatePrivateKeysForbidden) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] publicApiServiceCreatePrivateKeysForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysForbidden) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] publicApiServiceCreatePrivateKeysForbidden  %+v", 403, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysForbidden) GetPayload() interface{} {
	return o.Payload
}

func (o *PublicAPIServiceCreatePrivateKeysForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceCreatePrivateKeysNotFound creates a PublicAPIServiceCreatePrivateKeysNotFound with default headers values
func NewPublicAPIServiceCreatePrivateKeysNotFound() *PublicAPIServiceCreatePrivateKeysNotFound {
	return &PublicAPIServiceCreatePrivateKeysNotFound{}
}

/*
PublicAPIServiceCreatePrivateKeysNotFound describes a response with status code 404, with default header values.

Returned when the resource does not exist.
*/
type PublicAPIServiceCreatePrivateKeysNotFound struct {
	Payload string
}

// IsSuccess returns true when this public Api service create private keys not found response has a 2xx status code
func (o *PublicAPIServiceCreatePrivateKeysNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this public Api service create private keys not found response has a 3xx status code
func (o *PublicAPIServiceCreatePrivateKeysNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this public Api service create private keys not found response has a 4xx status code
func (o *PublicAPIServiceCreatePrivateKeysNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this public Api service create private keys not found response has a 5xx status code
func (o *PublicAPIServiceCreatePrivateKeysNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this public Api service create private keys not found response a status code equal to that given
func (o *PublicAPIServiceCreatePrivateKeysNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the public Api service create private keys not found response
func (o *PublicAPIServiceCreatePrivateKeysNotFound) Code() int {
	return 404
}

func (o *PublicAPIServiceCreatePrivateKeysNotFound) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] publicApiServiceCreatePrivateKeysNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysNotFound) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] publicApiServiceCreatePrivateKeysNotFound  %+v", 404, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysNotFound) GetPayload() string {
	return o.Payload
}

func (o *PublicAPIServiceCreatePrivateKeysNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPublicAPIServiceCreatePrivateKeysDefault creates a PublicAPIServiceCreatePrivateKeysDefault with default headers values
func NewPublicAPIServiceCreatePrivateKeysDefault(code int) *PublicAPIServiceCreatePrivateKeysDefault {
	return &PublicAPIServiceCreatePrivateKeysDefault{
		_statusCode: code,
	}
}

/*
PublicAPIServiceCreatePrivateKeysDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type PublicAPIServiceCreatePrivateKeysDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this public Api service create private keys default response has a 2xx status code
func (o *PublicAPIServiceCreatePrivateKeysDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this public Api service create private keys default response has a 3xx status code
func (o *PublicAPIServiceCreatePrivateKeysDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this public Api service create private keys default response has a 4xx status code
func (o *PublicAPIServiceCreatePrivateKeysDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this public Api service create private keys default response has a 5xx status code
func (o *PublicAPIServiceCreatePrivateKeysDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this public Api service create private keys default response a status code equal to that given
func (o *PublicAPIServiceCreatePrivateKeysDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the public Api service create private keys default response
func (o *PublicAPIServiceCreatePrivateKeysDefault) Code() int {
	return o._statusCode
}

func (o *PublicAPIServiceCreatePrivateKeysDefault) Error() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] PublicApiService_CreatePrivateKeys default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysDefault) String() string {
	return fmt.Sprintf("[POST /public/v1/submit/create_private_keys][%d] PublicApiService_CreatePrivateKeys default  %+v", o._statusCode, o.Payload)
}

func (o *PublicAPIServiceCreatePrivateKeysDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *PublicAPIServiceCreatePrivateKeysDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
