// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Immutablewebauthnv1AuthenticatorTransport immutablewebauthnv1 authenticator transport
//
// swagger:model immutablewebauthnv1AuthenticatorTransport
type Immutablewebauthnv1AuthenticatorTransport string

func NewImmutablewebauthnv1AuthenticatorTransport(value Immutablewebauthnv1AuthenticatorTransport) *Immutablewebauthnv1AuthenticatorTransport {
	return &value
}

// Pointer returns a pointer to a freshly-allocated Immutablewebauthnv1AuthenticatorTransport.
func (m Immutablewebauthnv1AuthenticatorTransport) Pointer() *Immutablewebauthnv1AuthenticatorTransport {
	return &m
}

const (

	// Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTBLE captures enum value "AUTHENTICATOR_TRANSPORT_BLE"
	Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTBLE Immutablewebauthnv1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_BLE"

	// Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTINTERNAL captures enum value "AUTHENTICATOR_TRANSPORT_INTERNAL"
	Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTINTERNAL Immutablewebauthnv1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_INTERNAL"

	// Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTNFC captures enum value "AUTHENTICATOR_TRANSPORT_NFC"
	Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTNFC Immutablewebauthnv1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_NFC"

	// Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTUSB captures enum value "AUTHENTICATOR_TRANSPORT_USB"
	Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTUSB Immutablewebauthnv1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_USB"

	// Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTHYBRID captures enum value "AUTHENTICATOR_TRANSPORT_HYBRID"
	Immutablewebauthnv1AuthenticatorTransportAUTHENTICATORTRANSPORTHYBRID Immutablewebauthnv1AuthenticatorTransport = "AUTHENTICATOR_TRANSPORT_HYBRID"
)

// for schema
var immutablewebauthnv1AuthenticatorTransportEnum []interface{}

func init() {
	var res []Immutablewebauthnv1AuthenticatorTransport
	if err := json.Unmarshal([]byte(`["AUTHENTICATOR_TRANSPORT_BLE","AUTHENTICATOR_TRANSPORT_INTERNAL","AUTHENTICATOR_TRANSPORT_NFC","AUTHENTICATOR_TRANSPORT_USB","AUTHENTICATOR_TRANSPORT_HYBRID"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		immutablewebauthnv1AuthenticatorTransportEnum = append(immutablewebauthnv1AuthenticatorTransportEnum, v)
	}
}

func (m Immutablewebauthnv1AuthenticatorTransport) validateImmutablewebauthnv1AuthenticatorTransportEnum(path, location string, value Immutablewebauthnv1AuthenticatorTransport) error {
	if err := validate.EnumCase(path, location, value, immutablewebauthnv1AuthenticatorTransportEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this immutablewebauthnv1 authenticator transport
func (m Immutablewebauthnv1AuthenticatorTransport) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateImmutablewebauthnv1AuthenticatorTransportEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this immutablewebauthnv1 authenticator transport based on context it is used
func (m Immutablewebauthnv1AuthenticatorTransport) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
