// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1APIKeyParams v1 Api key params
//
// swagger:model v1ApiKeyParams
type V1APIKeyParams struct {

	// @inject_tag: validate:"required,max=40"
	//
	// Human-readable name for an API Key.
	// Required: true
	APIKeyName *string `json:"apiKeyName"`

	// @inject_tag: validate:"hexadecimal,len=66"
	//
	// The public component of a cryptographic key pair used to sign messages and transactions.
	// Required: true
	PublicKey *string `json:"publicKey"`
}

// Validate validates this v1 Api key params
func (m *V1APIKeyParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAPIKeyName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePublicKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1APIKeyParams) validateAPIKeyName(formats strfmt.Registry) error {

	if err := validate.Required("apiKeyName", "body", m.APIKeyName); err != nil {
		return err
	}

	return nil
}

func (m *V1APIKeyParams) validatePublicKey(formats strfmt.Registry) error {

	if err := validate.Required("publicKey", "body", m.PublicKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 Api key params based on context it is used
func (m *V1APIKeyParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1APIKeyParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1APIKeyParams) UnmarshalBinary(b []byte) error {
	var res V1APIKeyParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
