// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1DeleteUsersIntent v1 delete users intent
//
// swagger:model v1DeleteUsersIntent
type V1DeleteUsersIntent struct {

	// @inject_tag: validate:"required,dive,required,uuid"
	//
	// A list of User IDs.
	// Required: true
	UserIds []string `json:"userIds"`
}

// Validate validates this v1 delete users intent
func (m *V1DeleteUsersIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1DeleteUsersIntent) validateUserIds(formats strfmt.Registry) error {

	if err := validate.Required("userIds", "body", m.UserIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 delete users intent based on context it is used
func (m *V1DeleteUsersIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DeleteUsersIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DeleteUsersIntent) UnmarshalBinary(b []byte) error {
	var res V1DeleteUsersIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
