// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1DeleteUserTagsIntent v1 delete user tags intent
//
// swagger:model v1DeleteUserTagsIntent
type V1DeleteUserTagsIntent struct {

	// @inject_tag: validate:"required,dive,required,uuid"
	//
	// A list of User Tag IDs.
	// Required: true
	UserTagIds []string `json:"userTagIds"`
}

// Validate validates this v1 delete user tags intent
func (m *V1DeleteUserTagsIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUserTagIds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1DeleteUserTagsIntent) validateUserTagIds(formats strfmt.Registry) error {

	if err := validate.Required("userTagIds", "body", m.UserTagIds); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this v1 delete user tags intent based on context it is used
func (m *V1DeleteUserTagsIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1DeleteUserTagsIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1DeleteUserTagsIntent) UnmarshalBinary(b []byte) error {
	var res V1DeleteUserTagsIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
