// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1SignRawPayloadIntent v1 sign raw payload intent
//
// swagger:model v1SignRawPayloadIntent
type V1SignRawPayloadIntent struct {

	// encoding
	// Required: true
	Encoding *V1PayloadEncoding `json:"encoding"`

	// hash function
	// Required: true
	HashFunction *V1HashFunction `json:"hashFunction"`

	// @inject_tag: validate:"required"
	//
	// Raw unsigned payload to be signed.
	// Required: true
	Payload *string `json:"payload"`

	// @inject_tag: validate:"required,uuid"
	//
	// Unique identifier for a given Private Key.
	// Required: true
	PrivateKeyID *string `json:"privateKeyId"`
}

// Validate validates this v1 sign raw payload intent
func (m *V1SignRawPayloadIntent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEncoding(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHashFunction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SignRawPayloadIntent) validateEncoding(formats strfmt.Registry) error {

	if err := validate.Required("encoding", "body", m.Encoding); err != nil {
		return err
	}

	if err := validate.Required("encoding", "body", m.Encoding); err != nil {
		return err
	}

	if m.Encoding != nil {
		if err := m.Encoding.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("encoding")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("encoding")
			}
			return err
		}
	}

	return nil
}

func (m *V1SignRawPayloadIntent) validateHashFunction(formats strfmt.Registry) error {

	if err := validate.Required("hashFunction", "body", m.HashFunction); err != nil {
		return err
	}

	if err := validate.Required("hashFunction", "body", m.HashFunction); err != nil {
		return err
	}

	if m.HashFunction != nil {
		if err := m.HashFunction.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("hashFunction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("hashFunction")
			}
			return err
		}
	}

	return nil
}

func (m *V1SignRawPayloadIntent) validatePayload(formats strfmt.Registry) error {

	if err := validate.Required("payload", "body", m.Payload); err != nil {
		return err
	}

	return nil
}

func (m *V1SignRawPayloadIntent) validatePrivateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("privateKeyId", "body", m.PrivateKeyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this v1 sign raw payload intent based on the context it is used
func (m *V1SignRawPayloadIntent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEncoding(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHashFunction(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SignRawPayloadIntent) contextValidateEncoding(ctx context.Context, formats strfmt.Registry) error {

	if m.Encoding != nil {
		if err := m.Encoding.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("encoding")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("encoding")
			}
			return err
		}
	}

	return nil
}

func (m *V1SignRawPayloadIntent) contextValidateHashFunction(ctx context.Context, formats strfmt.Registry) error {

	if m.HashFunction != nil {
		if err := m.HashFunction.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("hashFunction")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("hashFunction")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1SignRawPayloadIntent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SignRawPayloadIntent) UnmarshalBinary(b []byte) error {
	var res V1SignRawPayloadIntent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
